name: Java CI with Gradle

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build shadowJar
    - name: Upload Velocity artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Trevor Velocity
        path: velocity/build/libs/
    - name: Upload BungeeCord artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Trevor BungeeCord
        path: bungee/build/libs/
